version: '3.7'
# Define services
services:
# MongoDB service
  mongod:
    image: mongo:latest
    container_name: mongod
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db

# Scrappr Network
networks:
  - scrappr-network
