version: '3.7'
# Define services
services:
  scrapy-splash:
    image: scrapinghub/splash
    container_name: scrapy-splash
    restart: always
    environment:
      - SPLASH_URL=http://splash:8050
    ports:
      - "8050:8050"
    command: --max-timeout 3600
