import scrapy


class WalmartGroceryItem(scrapy.Item):
    id = scrapy.Field()
    title = scrapy.Field()
    product_url = scrapy.Field()
    img_url_list = scrapy.Field()
    price = scrapy.Field()
    brand= scrapy.Field()
    off_price = scrapy.Field()
    shortDescription = scrapy.Field()
    longDescription = scrapy.Field()
    productHighlights = scrapy.Field()
    specifications = scrapy.Field()
    warranty = scrapy.Field()
    rating = scrapy.Field()
    badge = scrapy.Field()
    returns_back = scrapy.Field()
    reviews = scrapy.Field()
    availabilityStatus = scrapy.Field()
    availableQuantity = scrapy.Field()
    manufacturerProductId = scrapy.Field()
    model = scrapy.Field()
    type = scrapy.Field()
    conditionType = scrapy.Field()
    sellerId = scrapy.Field()
    offerId = scrapy.Field()
    offerType = scrapy.Field()
    orderLimit = scrapy.Field()
    sellerType = scrapy.Field()
    upc = scrapy.Field()
    sellerDisplayName = scrapy.Field()
    sellerName = scrapy.Field()
    location = scrapy.Field()
    productTypeId = scrapy.Field()
    numberOfReviews = scrapy.Field()
    returnPolicy = scrapy.Field()
    salesUnit = scrapy.Field()
    keywords = scrapy.Field()
    category = scrapy.Field()
